### ISSUE TITLE
Industry users should not be able to request access to more than operator 

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#554] opened 2024-01-11 20:11 UTC
Describe the Bug:

Currently, each BCeID is associated with only one operator (contractors have separate BCeIDs for each company they work with). When we need to get a user's operator, we often look it up via the user_operator table (something like operator = UserOperator.objects.get(user=current_user).operator_id). In theory, this works fine. In practice, sometimes users are able to submit more than one request to join an operator, and then we start seeing this error:

```
raise self.model.MultipleObjectsReturned(
registration.models.UserOperator.MultipleObjectsReturned: get() returned more than one UserOperator -- it returned 2!
```

In the future, requirements may change and we may need to give users access to more than one operator. For now, however, we should restrict them to one request (I think?). This could involve some or all of the following:
- be careful about allowing users access to the select-operator form after they've already submitted a request (pending page helped with this)
- unique constraint on the db so that there can only be one row per user in the user_operator table

Probability (how likely the bug is to happen, scored from 1-5):
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5):
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by BCerki** [comment] 2024-01-11 20:13
@Sepehr-Sobhani , I finished writing this ticket and then realize we'd talked about this before and you may already have written one 🤦. If yes, we could combine them.

@dleard , what do you think about the proposed fix here? I ~think it would easy enough to remove a unique constraint if requirements change

**Comment by Sepehr-Sobhani** [comment] 2024-01-11 20:34
> @Sepehr-Sobhani , I finished writing this ticket and then realize we'd talked about this before and you may already have written one 🤦. If yes, we could combine them.
> 
> @dleard , what do you think about the proposed fix here? I ~think it would easy enough to remove a unique constraint if requirements change

I haven't. It was always an open question and we never came to a conclusion. Thank you for creating this ticket.

**Comment by marcellmueller** [comment] 2024-01-11 22:47
All good, this might be a duplicate of #511 so feel free to combine them and close one.

**Comment by BCerki** [comment] 2024-02-26 16:37
Should be fixed by https://github.com/orgs/bcgov/projects/122/views/2?pane=issue&itemId=53044195

**Comment by andrea-williams** [comment] 2024-03-25 20:13
Closing - already completed

**Closed by andrea-williams** 2024-03-25 20:13 UTC
Labels: Deletion Candidate, Task
