### ISSUE TITLE
UAT Bug- (ext. user) unable to undo operator selection after access request is sent

### ISSUE THREAD

**Issue by TammieV-BCG** [bcgov/cas-registration#2515] opened 2024-11-22 00:20 UTC
#### Describe the Bug:
unable to undo operator selection after access request is sent

#### Steps to reproduce the behaviour:
I am supposed to choose the registered operator, however, I chose Fresh Operator, and after the access request sent, I was stuck in this page, and I was not able to re-choose the “correct” operator  

#### Additional information:

Browser: [e.g. chrome, safari]
Version: [e.g. 22]

#### Additional Context
not connected to a ticket but will lead to lots of unnecessary contact with DST to undo Access request 
-

**Comment by zoeyli-46** [comment] 2024-11-25 17:04
PO/team's input: it is an edge case that they would send an admin access request to the wrong operator, if they end up doing that then DST will just decline the access request. 

Should we close or icebox this ticket?

**Comment by patrickisaac** [comment] 2024-12-17 19:13
Refinement Notes:
- De-prioritizing based on team discussion

**Comment by patriciarussellCAS** [comment] 2024-12-17 19:16
@TammieV-BCG - this is not a bug, so we will close this ticket. There is future work planned for user access as well.

**Closed** 2024-12-30 22:19 UTC
Labels: Bug
