### ISSUE TITLE
Industrial Operator can submit a registration form for an operation

### ISSUE THREAD

**Issue by NicoleGovvy** [bcgov/cas-registration#78] opened 2023-09-07 19:20 UTC
#### Description:

As an IO, I want to register an operation (facility) so that the operation will be exempt from carbon tax. Note: #26 covered adding an operation to the app, but just adding it shouldn't automatically register it.

#### Acceptance Criteria:

Given I am logged in to the Registration app with my Business BCeID account and I have been granted "admin" role for my operator
When I navigate to the Operation (facility) Details page
Then I can view the existing operations associated with my operator
And I can register them

#### Development Checklist:

- [ ] Checklist item
- [ ] Checklist item
- [ ] Checklist item
- [ ] Meets the DOD

**Definition of Ready** (Note: If any of these points are not applicable, mark N/A)

- [ ] User story is included
- [ ] User role and type are identified
- [ ] Acceptance criteria are included
- [ ] Wireframes are included (if required)
- [ ] Design / Solution is accepted by Product Owner
- [ ] Dependencies are identified (technical, business, regulatory/policy)
- [ ] Story has been estimated (under 13 pts)

·**Definition of Done** (Note: If any of these points are not applicable, mark N/A)

- [ ] Acceptance criteria are tested by the CI pipeline
- [ ] UI meets accessibility requirements
- [ ] Configuration changes are documented, documentation and designs are updated
- [ ] Passes code peer-review
- [ ] Passes QA of Acceptance Criteria with verification in Dev and Test
- [ ] Ticket is ready to be merged to main branch
- [ ] Can be demoed in Sprint Review
- [ ] Bugs or future work cards are identified and created
- [ ] Reviewed and approved by Product Owner

#### Notes:

-

**Comment by BCerki** [comment] 2023-09-11 21:24
Same as https://app.zenhub.com/workspaces/climate-action-secretariat-60ca4121764d710011481ca2/issues/gh/bcgov/cas-registration/26?

**Comment by BCerki** [comment] 2023-09-28 21:16
@nanyangpro, I don't think we're missing a wireframe around operations. We have a form for adding an operation: 
![image](https://github.com/bcgov/cas-registration/assets/77306764/f4a56b9a-1e1e-41b0-a6f3-d446122ad6c2)
But as discussed, adding an operation shouldn't automatically register it, so what does the workflow look like?

**Comment by hannavovk** [comment] 2023-10-05 00:45
@BCerki I think this is a duplicate of #26 actually - see my comments on #26. Submitting the completed form is equal to submitting the request to register an operation.

**Comment by hannavovk** [comment] 2023-10-12 02:42
At this time the scope of the app MVP is limited to registering operations for OBPS, so submitting the completed form is equivalent to submitting a request to register the operation. I.e. this is covered under #26. Once the scope is expanded to reporting-only operations we'll evaluate if any changes are needed or it will be covered by another workflow altogether.

**Closed by hannavovk** 2023-10-12 02:42 UTC
Labels: User Story, Backlog Refinement, Needs Wireframe
