### ISSUE TITLE
Reg\Operation - Operation status set to "Registered" conditionally

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#1991] opened 2024-07-23 23:48 UTC
#### Describe the task

We need to add functionality to our API that indicates whether a given operation is "fully registered".

A "fully registered" operation has data for all fields that are required in Reg Part 2, and an external user has officially submitted the registration form (i.e., they've clicked all 3 checkboxes on the last step of the form - see [here](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=13340-2186&t=5XIjxgIZUclh8O7b-1)).

No frontend work associated with this ticket.

#### Acceptance Criteria
- [x] if an operation does not have a contact with an assigned "Operation Representative", the status should be `Draft`
- [x] an operation must have at least one Operation Representative with a mailing address tied to their contact info. If this is not the case, the status should be `Draft`
- [x] if an operation has no facilities associated with it, the status should be `Draft`
- [x] if an operation does not have at least 1 reporting activity associated with it, the status should be `Draft`
- [x] if an operation does not have BOTH a "process flow diagram" doc AND a "boundary map" file associated with it, the status should be `Draft`
- [x] if an operation has data for all required fields but no external user has accepted the 3 checkboxes on the last step of the form, the status should be `Draft`
- [x] if an operation's registration category is New Entrant but there is no record for the operation in the `new_entrant` table, or if the record in new_entrant is incomplete, the status should be `Draft` - see #1906 
- [x] if an operation's registration category is Opt-in but there is no record for that operation in the `opt_in` table, or if the record in opt_in is incomplete, the status should be `Draft` - see #1952 
- [x] if an operation has data for all required fields and an external user representing the operator has accepted the 3 checkboxes and "submitted" the form, the status should be `Registered`
- [x] GET request for an operation by ID + GET request for all options should include in response the status of the operation/s

**Note: the operation status should be updated to "Registered" immediately after successful submission of the registration form. BORO IDs and BCGHG IDs will be manually issued later, so it is possible for an operation to have a status of "Registered" but be missing one/both a BORO ID or BCGHG ID**

#### Development Checklist

- [x] upon external user's submission of the Registration form, the status of the operation is set to "Registered" (unless contra-indicated by one of the AC above)
- [x] create pytests for each of the AC

#### Additional context

- will need this functionality for the purpose of determining which tiles on the main dashboard should be disabled/enabled (to help guide external users through the entire workflow in BCIERS)
- Reporting module will also have a need to fetch the data returned in this endpoint

**Comment by andrea-williams** [comment] 2024-08-27 20:48
Might not need this to be a separate ticket because we won't need a separate API endpoint - can just query the `status` on the operation by its ID. However, saving this ticket for now because the suggested test cases might be useful in the near future.

**Comment by patriciarussellCAS** [comment] 2024-09-10 22:29
Do we need any specific AC to differentiate between and LFO and SFO? Do SFOs have to include a facility in order to proceed? I think they do but wasn't sure where that landed.

**Comment by BCerki** [comment] 2024-09-19 18:46
@andrea-williams , for this one: `an operation must have at least one Operation Representative with a mailing address tied to their contact info. If this is not the case, the status should be Draft`. None of the fields in the address model are mandatory, so just checking if there's a foreign key doesn't tell us much. Are all of street address, municipality,  province and postal code necessary to be considered a complete address?

**Comment by andrea-williams** [comment] 2024-09-19 18:54
> @andrea-williams , for this one: `an operation must have at least one Operation Representative with a mailing address tied to their contact info. If this is not the case, the status should be Draft`. None of the fields in the address model are mandatory, so just checking if there's a foreign key doesn't tell us much. Are all of street address, municipality, province and postal code necessary to be considered a complete address?

I'm going to tentatively say yes. The only argument there might be against that is if the contact info is not within Canada (and therefore province & postal code won't apply). I'd recommend for now assuming that all of (mailing address, municipality, province, postal code) are required.

This highlights a potential larger issue I want to loop @patriciarussellCAS in on - during development of Reg 1 the indication was that contact info for all people would be restricted to Canada. I get the sense that's no longer necessarily the case, but wanted to double check with you? I'm thinking mostly of cases like "multiple operators" for an operation or parent companies - will contacts for those companies always be within Canada?

**Comment by patriciarussellCAS** [comment] 2024-09-19 22:40
Thanks @andrea-williams and @BCerki - this is on my list to discuss with BA at next week's collab. 
Here's what I think are the key questions: 
- Do all contacts and/or Operation Representatives need to have addresses in Canada? Y/N
- Can we allow them to register without complete information for the Operation Representative (so for example, if they haven't filled out the business mailing address info, can we still consider the registration "complete" - I know that technically this goes against the regulations, but I want to see if we can push this specific issue to later if possible)

Andrea - regarding address information for multiple operators and parent companies, I would expect those would need to be international, but I can confirm that as well. 

Did I miss anything?

**Comment by BCerki** [comment] 2024-09-20 15:31
@andrea-williams , me again... 
- `if an operation's registration category is New Entrant but there is no record for the operation in the new_entrant table, or if the record in new_entrant is incomplete`--we don't have a new entrant table. I think the required new entrant stuff is only the signed statuatory declaration?
- `if an operation's registration category is Opt-in but there is no record for that operation in the opt_in table, or if the record in opt_in is incomplete`--everything in `opted_in_operation_detail` is optional. Am I just checking for the existence of the foreign key?
- I'm creating a service to check everything is filled and it'll go into `/v2/operations/{operation_id}/registration/submission` before the `update_status` service runs. If the anything is incomplete, the status won't be changed to registered, but should I also throw an exception (or something?) to give the user feedback that the status couldn't be changed to registered?

**Comment by andrea-williams** [comment] 2024-10-01 21:05
for the opt-in operations - you're not going to like this, but if an operation is an opt-in, we'll want to confirm that we have explicit yes or no answers to each of the bool questions in the form.

**Comment by andrea-williams** [comment] 2024-10-01 21:53
looping in @zoeyli-46  regarding your last point - should an external user receive some visual indication that their operation couldn't be set to "registered" because of <whatever reason>?

**Comment by andrea-williams** [comment] 2024-10-01 21:54
for new entrants, we'll just want to make sure that they have uploaded a file for their stat dec

**Comment by zoeyli-46** [comment] 2024-10-02 11:41
Wouldn't we show an error on the page that the error is happening, so that they cannot continue to the next page? In what scenario would the operation not be able to be set to registered? If the scenarios for not being able to register it are the ones in the AC of this ticket, i.e.: 'if an operation does not have a contact with an assigned "Operation Representative", the status should be Draft' etc. then wouldn't we just on the same page have an error so that the user couldn't continue? Showing the error directly on the field?

If we can't show the errors in the fields on the page, then maybe we can have an error page after they click submit? Something like this: [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=20686-236&t=3HIOg77bZ7w19g9e-4)?

**Comment by andrea-williams** [comment] 2024-10-02 15:54
> Wouldn't we show an error on the page that the error is happening, so that they cannot continue to the next page? In what scenario would the operation not be able to be set to registered? If the scenarios for not being able to register it are the ones in the AC of this ticket, i.e.: 'if an operation does not have a contact with an assigned "Operation Representative", the status should be Draft' etc. then wouldn't we just on the same page have an error so that the user couldn't continue? Showing the error directly on the field?
> 
> If we can't show the errors in the fields on the page, then maybe we can have an error page after they click submit? Something like this: [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=20686-236&t=3HIOg77bZ7w19g9e-4)?

Fair point. As long as the user is using the UI as intended, the error would appear on the relevant page. It would only be when a user is monkeying around (i.e., sending data via a CURL request rather than via the UI) that we would get into that situation.

@BCerki to answer your 3rd question, let's assume for now that no exception/feedback is needed if the status isn't "Registered".

**Comment by Sepehr-Sobhani** [comment] 2024-10-03 19:01
@zoeyli-46 @andrea-williams

Hey, sorry to jump in here! I totally get the points being made, and I agree that we don’t need to worry about showing an error for someone who's deliberately bypassing the app. However, my concern is more about those rare cases where something goes wrong on our side—like a bug in the code that slipped through the cracks.

Imagine the user gets all the way to the last page, tries to submit, and we block them, but without showing an error. They’d be stuck clicking the button with no feedback, which would be a bit awkward. So, I think we should display the error just in case, even if it’s unlikely, so we can investigate later if needed.

cc: @BCerki

**Comment by zoeyli-46** [comment] 2024-10-03 19:03
That's fair @Sepehr-Sobhani! would this design be applicable for the scenario you mentioned? [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=20686-236&t=TiJxn6znYKYcccof-4)

**Comment by andrea-williams** [comment] 2024-10-03 19:04
> @zoeyli-46 @andrea-williams
> 
> Hey, sorry to jump in here! I totally get the points being made, and I agree that we don’t need to worry about showing an error for someone who's deliberately bypassing the app. However, my concern is more about those rare cases where something goes wrong on our side—like a bug in the code that slipped through the cracks.
> 
> Imagine the user gets all the way to the last page, tries to submit, and we block them, but without showing an error. They’d be stuck clicking the button with no feedback, which would be a bit awkward. So, I think we should display the error just in case, even if it’s unlikely, so we can investigate later if needed.
> 
> cc: @BCerki

@BCerki  - @Sepehr-Sobhani  has stepped in to shatter all your hopes and dreams, Marcel-style!

**Comment by Sepehr-Sobhani** [comment] 2024-10-03 19:57
> That's fair @Sepehr-Sobhani! would this design be applicable for the scenario you mentioned? [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=20686-236&t=TiJxn6znYKYcccof-4)

Thank you for creating the design so quickly, @zoeyli-46! However, I suggest not dedicating a separate page for this purpose since it's a rare occurrence. I believe having a simple error alert on the same page would make more sense, as we already have that in other forms.

**Comment by Sepehr-Sobhani** [comment] 2024-10-03 19:58
> > @zoeyli-46 @andrea-williams
> > Hey, sorry to jump in here! I totally get the points being made, and I agree that we don’t need to worry about showing an error for someone who's deliberately bypassing the app. However, my concern is more about those rare cases where something goes wrong on our side—like a bug in the code that slipped through the cracks.
> > Imagine the user gets all the way to the last page, tries to submit, and we block them, but without showing an error. They’d be stuck clicking the button with no feedback, which would be a bit awkward. So, I think we should display the error just in case, even if it’s unlikely, so we can investigate later if needed.
> > cc: @BCerki
> 
> @BCerki - @Sepehr-Sobhani has stepped in to shatter all your hopes and dreams, Marcel-style!

Sorry @BCerki! 😄

**Comment by BCerki** [comment] 2024-10-03 20:13
> > That's fair @Sepehr-Sobhani! would this design be applicable for the scenario you mentioned? [Figma](https://www.figma.com/design/LsDmLDCdnJqI8UahyqvOD8/BCIERS-Designs?node-id=20686-236&t=TiJxn6znYKYcccof-4)
> 
> Thank you for creating the design so quickly, @zoeyli-46! However, I suggest not dedicating a separate page for this purpose since it's a rare occurrence. I believe having a simple error alert on the same page would make more sense, as we already have that in other forms.

To keep the scope of this ticket closer to the original, I can do the messaging via the existing API alert error:
![image](https://github.com/user-attachments/assets/c528976f-e662-4644-b139-6cf35f9b1564)

**Closed** 2024-10-23 20:36 UTC
Labels: Task
