### ISSUE TITLE
Reg\Registration workflow - continue Registration flow is confusing/broken [6]

### ISSUE THREAD

**Issue by andrea-williams** [bcgov/cas-registration#2445] opened 2024-11-05 22:30 UTC
#### Describe the Bug:

For external users who have 1 or more unregistered operations tied to their operator, they see a "Continue Registration" button from their operations grid, but clicking the button takes them to the Operation Information page, which they can't use to register. 

Clicking the "Continue Registration" button should direct them to the registration multistep form, ideally with the operation pre-selected.

#### Probability: 4

(How likely the bug is to happen, scored from 1-5. For example, probability of 5 is something like "it happens to all users every time they log in." whereas probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

#### Impact: 2

(How bad the bug is when it does happen, scored from 1-5. For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected." whereas effect of 1 is "It makes some styling look a little bit weird.")

<img src="https://www.getzephyr.com/sites/default/files/riksk%20matrix.jpg" alt="Bug Matrix" width="250" height="250"/>

#### Steps to reproduce the behaviour:

1. Sign in as an industry user with access to an operator (e.g., `bc-cas-dev`)
2. Go to the Operations grid in Admin module
3. Click "Continue Registration" button next to an operation that isn't yet registered (some of our mock operations are outdated and won't have "Continue Registration" buttons, but at least one should)
4. Observe bug - you're redirected to the Operation Information page, not the registration workflow. You can't actually register from this page

The workaround (that is not at all intuitive for users and we need to fix) is to use either the Registration dashboard tile or the "Add and register a new operation" button in the Admin module, then select the relevant operation from the dropdown in the registration multistep form.

Recommended fix: the "Continue Registration" href should take users to the registration multistep form, ideally with the relevant operation pre-selected in the form.

#### Additional information:

Browser: [e.g. chrome, safari]
Version: [e.g. 22]

#### Additional Context

-

**Comment by rdromey** [comment] 2024-11-07 21:26
Duplicate of #2270

**Closed by rdromey** 2024-11-07 21:26 UTC
Labels: Bug
