### ISSUE TITLE
UAT Bug?-Text says “…2023 or 2024” not 2024 or 2025

### ISSUE THREAD

**Issue by TammieV-BCG** [bcgov/cas-registration#2511] opened 2024-11-21 23:49 UTC
#### Describe the Bug:
Text says “…2023 or 2024” not 2024 or 2025 

#### Steps to reproduce the behaviour:
1. Navigate to add facility 
2. Text has 2023/24 instead of 2024/25 

#### Screenshots:
![Image](https://github.com/user-attachments/assets/c61a3da6-87ef-4f1e-8151-ba3ae685330b)

#### Additional information:
Browser: chrome and edge

#### Additional Context
User story: As an External User, given that I am adding a new facility, if my answer to Did this facility begin operations in 2024 or 2025 is "yes", then I can see the “Date of the facility starting operations:”

Link to UAT ticket: https://teams.microsoft.com/l/entity/com.microsoft.teamspace.tab.planner/mytasks?tenantId=6fdb5200-3d0d-4a8a-b036-d3685e359adc&webUrl=https%3A%2F%2Ftasks.teams.microsoft.com%2Fteamsui%2FpersonalApp%2Falltasklists&context=%7B%22subEntityId%22%3A%22%2Fv1%2Fplan%2FbyyJUkJggkaPhsw6jAP-oWUAGWDg%2Ftask%2FU27KAtQaAkGLScHEBRcxaGUADJWl%22%7D
-

**Comment by zoeyli-46** [comment] 2024-11-22 05:17
@andrea-williams is the year that shows up dynamic? I.e., it says 2023 and 2024 because its not hard coded, and its showing the current and past year?

**Comment by zoeyli-46** [comment] 2024-12-04 23:58
@Sepehr-Sobhani @BCerki do either of you know, if the year that shows up is dynamic? I.e., it says 2023 and 2024 because its not hard coded, and its showing the current and past year?

**Comment by BCerki** [comment] 2024-12-05 00:14
It's dynamic, it shows the current year and last year:
```
is_current_year: {
      type: "boolean",
      title: `Did this facility begin operations in ${
        currentYear - 1
      } or ${currentYear}?`,
      default: false,
    },
```

**Comment by zoeyli-46** [comment] 2024-12-05 01:20
@TammieV-BCG we can close this ticket. its not a bug, it will show the current and last year so when the user is viewing it during registration then it will show the correct years 2024 /2025

**Closed** 2024-12-05 01:20 UTC
Labels: Bug
