### ISSUE TITLE
BCIERS\Dashboard - Internal user, pending approval, sees pending message

### ISSUE THREAD

**Issue by Sepehr-Sobhani** [bcgov/cas-registration#2058] opened 2024-08-08 23:48 UTC
#### Describe the task

In Reg1, we had a message to inform pending internal users that their request is pending approval. However, in Reg2, we haven't set up anything for that scenario.
Location of the page that shows the message based on the role(`FrontEndRoles.CAS_PENDING`): `/bciers/apps/registration1/app/(authenticated)/dashboard/page.tsx`

#### Dev Tasks
- [x] In `bciers/apps/dashboard/app/dashboard/page.tsx` add code related to displaying card "dashboard-pending-message",  similar to `bciers/apps/administration/app/page.tsx`
- [x] In `bciers/apps/administration/app/page.tsx` remove code related to displaying card "dashboard-pending-message"
- [x] in `bciers/apps/dashboard/middlewares/withAuthorizationDashboard.ts` refactor code:
**CHANGE**
```
  // Should the user be redirected to the onboarding page?
      if (token.app_role.includes("pending")) {
        const url = request.nextUrl.clone();
        url.pathname = "/registration";

        return NextResponse.rewrite(url);
      }
```
**TO**
```
   if (token.app_role.includes("pending")) {
        if (pathname.endsWith("/dashboard")) {
          return next(request, _next);
        } else {
          return NextResponse.redirect(new URL(`/dashboard`, request.url));
        }
      }
```
- [x] Update file `bciers/apps/dashboard/tests/routes/dashboard/page.test.tsx`

#### Acceptance Criteria

- [ ] Internal Users that are not approved yet, should see a message like what we have in `/bciers/apps/registration1/app/(authenticated)/dashboard/page.tsx`
- [ ] Internal Users that are not approved yet, should not be able to go to any other page by manually changing the URL.
- http://localhost:3000/administration
- http://localhost:3000/coam
- http://localhost:3000/registration
- http://localhost:3000/reporting

**Comment by shon-button** [comment] 2024-09-04 17:58
@patriciarussellCAS

Reachable at:
https://cas-bciers-frontend-dev.apps.silver.devops.gov.bc.ca


### Test Login IDIR\cas_pending
1. Navigate to `http://localhost:3000`
3. Click button "Log in with IDIR"
4. Sign in to Keycloak using your IDIR
**Expected Results**   
   - Common dashboard with `Pending approval...` displays.
   - Bread crumbs display `Dashboard`
![image](https://github.com/user-attachments/assets/662b66ba-dcac-4f7e-a5b8-545c7c7d26d1)

**Comment by patriciarussellCAS** [comment] 2024-09-08 15:56
Because I have approval already I'm unable to see this status. If someone could quickly show this workflow to me I can close this ticket.

**Comment by patriciarussellCAS** [comment] 2024-09-13 19:55
I have confirmed that I see this message on the dashboard when I am an internal user waiting for approval. 
I have noted my question about this flow in #2167 so will close this ticket and address any other issues in 2167.

**Closed by patriciarussellCAS** 2024-09-13 19:55 UTC
Labels: Task
