### ISSUE TITLE
Sometimes dashboard tiles are missing for bceid users [6]

### ISSUE THREAD

**Issue by BCerki** [bcgov/cas-registration#471] opened 2023-12-21 21:35 UTC
Describe the Bug:

I haven't figured out how to reproduce this, but sometimes when logging in with our test bceid, the dashboard is completely empty of tiles or missing tiles.

Probability (how likely the bug is to happen, scored from 1-5): 2?
(For example, probability of 5 is something like "it happens to all users every time they log in."
Probability of 1 "only happens to certain users when a really specific and unlikely path is followed.")

Effect (how bad the bug is when it does happen, scored from 1-5): 4
(For example, effect of 5 is "the entire app crashes and makes it unusable for all users" or "the bug causes the wrong data to be saved, with critical information (e.g. payment) being affected."
Effect of 1 is "It makes some styling look a little bit weird.")

Steps to reproduce the behaviour:

Screenshots:

Additional information:

- Browser: [e.g. chrome, safari]
- Version: [e.g. 22]
- Additional context

**Comment by shon-button** [comment] 2024-01-03 18:14
@BCerki 

As you mentioned, we have not been able to capture reproduction steps to this "infrequent?" issue but, it might be caused by a race condition between setting an authenticated user's role from our api response and importing the role tiles within the dashboard component.

In attempt to correct this possible race condition, I have added code (in develop branch) in the dashboard component `client/app/(authenticated)/dashboard/page.tsx` so to import the tiles only after the role is defined: `if (typeof window !== "undefined" && role)`

**Comment by dleard** [comment] 2024-01-05 01:03
A breadcrumb to follow: If the tiles show up blank, changing from the current browser tab and back again shows the tiles. This tab swap also fixes an issue whre a new user's identity_provider is not populated in the session object, resulting in an error when submitting the initial user form.

**Comment by shon-button** [comment] 2024-01-05 12:45
Thanks for the insights on this issue.
Are there any reproduction steps or troubleshooting notes (consoles errors from the servers or browsers, etc.)?

**Comment by BCerki** [comment] 2024-01-30 19:19
I haven't come across this bug since the tab-changing thing was fixed, so I ~think this bug might be fixed.

**Comment by dleard** [comment] 2024-01-30 23:37
Yep! This was fixed when we fixed the issue with the session not loading properly. Closing.

**Closed by dleard** 2024-01-30 23:37 UTC
Labels: Deletion Candidate, Bug, 🚀 in gh projects
